Params:
  PSFtype: insitu_zernike                 # voxel, zernike, pupil, zernike-vector, pupil-vector, insitu
  datatype: smlm
  loss_weight:                   # weighting factor for each loss term
    smooth: 0
  rej_threshold:                 # threshold for ourlier removal after initial learning, which are relative values or quantile for insitu PSF
    bias_z: 0.99
    mse: 0.8
    photon: 1.5
