# here the configuration for the usage of this repo should be specified
# if the paths are relative, they are relative to the current working direcotry (cwd)
# that would be reasonable to set to the repo dir
Paths:
  spline:
    win:
      cpp: dummy_win.dll
      cuda:
    mac:
      cpp: dummy_mac.so
    linux:
      cpp: dummy_linux.so
      cuda:
