# here the configuration for the usage of this repo should be specified
# if the paths are relative, they are relative to the current working direcotry (cwd)
# that would be reasonable to set to the repo dir
Params:
  # ------data specific parameters, should be updated for different data
  datapath: ''                  # full path to your data
  keyword: bead                 # keyword for your data file, used for automatic finding files with the same keyword
  savename: psfmodel            # full path to your result foder/filename
  subfolder: ""                 # keyword for subfolder name if each bead data is saved in a individual folder
  format: .tif                  # .mat, .tif, .czi
  stage_mov_dir: reverse         # normal, reverse: normal direction is where stage move towards the object when taking a z-stack bead data
  gain: 0.47
  ccd_offset: 100
  roi:
    roi_size: [61,61]           # vector of 2 or 3 element, roi size in [y, x] or [z, y, x]
    gauss_sigma: [12,12]          # blur kernel size, corresponding to dimensions defined in roi_size
    max_kernel: [13,13]           # maximum filter kernel size, corresponding to dimensions defined in roi_size
    peak_height: 0.2            # relative to maximum bead intensity, bead intensity below which are rejected
    max_bead_number: 20        # ignored by insitu PSF learning
    bead_radius: 0.0            # unit: micron
  pixel_size:                   # unit: micron
    x: 0.11
    y: 0.11
    z: 0.1
  FOV:                           # define FOV for bead selection, if x_center, y_center, radius are 0, select the full FOV
    y_center: 0
    x_center: 0
    radius: 0
    z_start: 0
    z_end: 0
    z_step: 1


  #--------type specific paramters, might require update for different data---------------------------
  dual:                          # parameters only for dual channel systems
    mirrortype: none          # up-down, left-right, none
    channel_arrange: left-right     # up-down, left-right
  fpi:                           # parameters only for 4pi systems
    modulation_period: 0.26      # unit: micron
    phase_dm: [2,0,-2]           # unit: radian
  LLS:                           # parameters only for lattice light-sheet psfs
    skew_const: [0,0]            # unit: pixel
  insitu:               
    frame_range: []     # set the frames to be loaded

  option:                         # mainly for pupil and zernike, insitu  learning
    imaging:                       
      emission_wavelength: 0.67    # unit: micron
      RI: 
        imm: 1.518
        med: 1.33
        cov: 1.518
      NA: 1.45
    insitu:
      stage_pos: 1.0               # 0 at the coverslip, positive when move towards the coverslip
      min_photon: 0.2              # quantile for rejecting low photon emitters
      partition_data: true
      partition_size: [11,200]     # number of z segments, maximum number of emitter per segment
      zernike_index: [5]           # for initial pupil, a vector of any size, if [], search for optimal zernike term
      zernike_coeff: [0.5]         # for initial pupil, value corresponding to the zernike index 
      zkorder_rank: L             # L, H: searching range of zernike coefficient (4,21), (21,45)    
      var_stagepos: true
      repeat: 2
      z_range: 2.0                 # unit: micron, z range of insitu psf model
    fpi:
      link_zernikecoeff: true
    model:
      pupilsize: 64                # unit: pixel
      n_max: 8                     # maximum zernike order
      zernike_nl: []
      blur_sigma: 0.5              # unit: pixel
      with_apoid: true
      const_pupilmag: false
      symmetric_mag: false
      with_IMM: false
      init_pupil_file: ""
  
  #--------following parameters usually don't need to be changed for the same type of psf learning, will be preset for each learning type
  PSFtype: pupil_vector                 # voxel, zernike, pupil, zernike-vector, pupil-vector, insitu
  channeltype: single            # single, multi, 4pi
  datatype: bead                 # bead, smlm
  
  loss_weight:                   # weighting factor for each loss term
    mse1: 1
    mse2: 1
    smooth: 0
    edge: 0.01
    psf_min: 1
    bg_min: 1
    photon_min: 0.000001
    Inorm: 0
    gxy_min: 10
  
  rej_threshold:                 # threshold for ourlier removal after initial learning, which are relative values or quantile for insitu PSF
    bias_z: 3
    mse: 3
    photon: 1.5
  
  usecuda: true                  # for spline localization
  plotall: true
  estimate_drift: false
  var_photon: true
  ref_channel: 0                 # index of the reference channel, for multi-channel system
  batch_size: 2000               # maximum number of beads or emitters to be optimized at one time
  iteration: 200                 # number of iterations for learning
  varname: ""                    # only for simulated data from matlab, the variable name for the data
  filelist: []                   # user can also give a list of data files, instead of giving the keyword or subfolder, data loading will skip automatic populate filelist 
  swaptif: true                  # permute x,y dimension of tif file

  
