# here the configuration for the usage of this repo should be specified
# if the paths are relative, they are relative to the current working direcotry (cwd)
# that would be reasonable to set to the repo dir
Params:
  # ------data specific parameters, should be updated for different data
  datapath: E:/EMBL files/data 2022/230202_Nup96SNAP_NC_M2/Nup96SNAP_BME_i50SM_ex200_zpos5um_NC_1                 # full path to your data
  keyword: Default.                 # keyword for your data file, used for automatic finding files with the same keyword
  savename: E:/EMBL files/data 2022/230202_Nup96SNAP_NC_M2/Nup96SNAP_BME_i50SM_ex200_zpos5um_NC_1/psfmodel_iter            # full path to your result foder/filename
  subfolder: ""                 # keyword for subfolder name if each bead data is saved in a individual folder
  format: .tif                  # .mat, .tif, .czi
  stage_mov_dir: normal         # normal, reverse: normal direction is where stage move towards the objective when taking a z-stack bead data
  gain: 0.2
  ccd_offset: 398.6
  roi:
    roi_size: [21,21]           # vector of 2 or 3 element, roi size in [y, x] or [z, y, x]
    gauss_sigma: [2,2]          # blur kernel size, corresponding to dimensions defined in roi_size
    max_kernel: [3,3]           # maximum filter kernel size, corresponding to dimensions defined in roi_size
    peak_height: 0.2            # relative to maximum bead intensity, bead intensity below which are rejected
    max_bead_number: 40        # ignored by insitu PSF learning
    bead_radius: 0.0            # unit: micron
  pixel_size:                   # unit: micron
    x: 0.127
    y: 0.116
    z: 0.05
  FOV:                           # define FOV for bead selection, if x_center, y_center, radius are 0, select the full FOV
    y_center: 0
    x_center: 0
    radius: 0
    z_start: 0
    z_end: -0
    z_step: 1


  #--------type specific paramters, might require update for different data---------------------------
  dual:                          # parameters only for dual channel systems
    mirrortype: up-down          # up-down, left-right
    channel_arrange: up-down     # up-down, left-right
  multi:
    channel_size: []
  fpi:                           # parameters only for 4pi systems
    modulation_period: 0.26      # unit: micron
  LLS:                           # parameters only for lattice light-sheet psfs
    skew_const: [0,0]            # unit: pixel
  insitu:               
    frame_range: [0,3000]     # set the frames to be loaded

  option:                         # mainly for pupil and zernike, insitu  learning
    imaging:                       
      emission_wavelength: 0.68    # unit: micron
      RI: 
        imm: 1.516
        med: 1.335
        cov: 1.516
      NA: 1.43
    insitu:
      stage_pos: 1               # 0 at the coverslip, positive when move towards the coverslip
      min_photon: 0.4              # quantile for rejecting low photon emitters
      partition_data: true         # select best emitters from each partition
      partition_size: [21,100]     # number of z segments, maximum number of emitter per segment
      zernike_index: [5]           # for initial pupil, a vector of any size, if [], search for optimal zernike term
      zernike_coeff: [0.5]         # for initial pupil, value corresponding to the zernike index 
      z_range: 2.0                 # unit: micron, z range of insitu psf model
      zkorder_rank: L             # L, H: searching range of zernike coefficient (4,21), (21,45)    
      var_stagepos: true          # estimate stage position
      repeat: 2                   # iteration number for insitu learning, the previous psf model will be used for the next iteration
      backgroundROI: []           # define the region where the emitters are at the coverslip, only for imaging close to the coverslip    
    fpi:
      link_zernikecoeff: true
      phase_dm: [2,0,-2]           # unit: radian
      sampleheight: 2
      var_sampleheight: false
      phase_delay_dir: descend     # phase delay between four channels, 'descend' or 'ascend'
    multi:
      defocus_offset: 0     # micron
      defocus_delay: -0.0    # micron
    model:
      pupilsize: 64                # unit: pixel
      n_max: 8                     # maximum zernike order
      zernike_nl: []               # set the Zernike terms for PSF learning, e.g. [(2,2),(2,-2)], if empty, all zernike terms defined by n_max will be used 
      blur_sigma: 0.5              # unit: pixel
      var_blur: true               # estimate blurring sigma
      with_apoid: true              # with theoretical apoidization term
      const_pupilmag: false         # pupil magnitude is constant and equal to one
      symmetric_mag: false          # pupil magnitude is circular symmetric
      with_IMM: false               # only used for agarose bead
      init_pupil_file: ""           # .h file from psf learning
      estimate_drift: false         # estimate lateral drift between each z slice
      var_photon: false             # estimate photon variation between each z slice
      bin: 2                        # upsamplling pixel size equal to camera pixel size divided by bin
      division: 40                  # number of divisions per lateral dimension for learning field-dependent aberration

  #--------following parameters usually don't need to be changed for the same type of psf learning, will be preset for each learning type
  PSFtype: insitu_zernike                 # voxel, zernike, pupil, zernike_vector, pupil_vector, insitu
  channeltype: single            # single, multi, 4pi
  datatype: smlm                 # bead, smlm
  
  loss_weight:                   # weighting factor for each loss term
    mse1: 1
    mse2: 1
    smooth: 0
    edge: 0.01
    psf_min: 1
    bg_min: 1
    photon_min: 1
    Inorm: 0
    gxy_min: 10
  
  rej_threshold:                 # threshold for ourlier removal after initial learning, which are relative values or quantile for insitu PSF
    bias_z: 0.99
    mse: 0.8
    photon: 1.5
  
  usecuda: true                  # for spline localization
  plotall: false
  ref_channel: 0                 # index of the reference channel, for multi-channel system
  batch_size: 1600               # maximum number of beads or emitters to be optimized at one time
  iteration: 200                 # number of iterations for learning
  varname: ""                    # only for simulated data from matlab, the variable name for the data
  filelist: []                   # user can also give a list of data files, instead of giving the keyword or subfolder, data loading will skip automatic populate filelist 
  swapxy: false                  # permute x,y dimension 

  
