Params:
  format: .tiff                  # .mat, .tif, .czi
  pixel_size:                   # unit: micron
    x: 0.104
    y: 0.104
  roi:
    roi_size: [37,27,27]           # vector of 2 or 3 element, roi size in [y, x] or [z, y, x]
    gauss_sigma: [6,2,2]          # blur kernel size, corresponding to dimensions defined in roi_size
    max_kernel: [9,3,3]           # maximum filter kernel size, corresponding to dimensions defined in roi_size

  LLS:                           # parameters only for lattice light-sheet psfs
    skew_const: [0,-0.7845]            # unit: pixel
  insitu:               
    frame_range: []     # set the frames to be loaded, only for .tif format

  option:   
    imaging:                       
      emission_wavelength: 0.6    # unit: micron
      RI: 
        imm: 1.334
        med: 1.334
        cov: 1.334
      NA: 1.1
    insitu:
      zernike_index: [5]           # for initial pupil, a vector of any size, if [], search for optimal zernike term
      zernike_coeff: [0.5]         # for initial pupil, value corresponding to the zernike index 
      partition_size: [21,100]     # number of z segments, maximum number of emitter per segment
      z_range: 2.0                 # unit: micron, z range of insitu psf model
    model:
      estimate_drift: true
